const controlBase = {
  border: '1px solid rgba(223, 229, 233, 0.18)',
  background: 'rgba(26, 32, 36, 0.92)',
  color: '#eef4f2',
}

export const styles = {
  panel: {
    position: 'fixed',
    top: 14,
    right: 14,
    zIndex: 20,
    width: 'min(360px, calc(100vw - 28px))',
    maxHeight: 'calc(100vh - 28px)',
    overflowY: 'auto',
    padding: 14,
    color: '#eef4f2',
    background: 'rgba(13, 18, 20, 0.92)',
    border: '1px solid rgba(223, 229, 233, 0.14)',
    borderRadius: 8,
    boxShadow: '0 18px 42px rgba(0, 0, 0, 0.26)',
    backdropFilter: 'blur(12px)',
    fontSize: 13,
  },
  fab: { position: 'fixed', top: 14, right: 14, zIndex: 20, ...controlBase, borderRadius: 8, padding: '9px 12px', cursor: 'pointer' },
  header: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 12 },
  title: { display: 'block', fontSize: 16, lineHeight: 1.15 },
  subtitle: { display: 'block', marginTop: 3, color: '#9fb3ac', fontSize: 12 },
  closeButton: { ...controlBase, width: 28, height: 28, borderRadius: 6, cursor: 'pointer' },
  section: { borderTop: '1px solid rgba(223, 229, 233, 0.12)', paddingTop: 10, marginTop: 10 },
  sectionButton: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: 0,
    padding: '0 0 8px',
    background: 'transparent',
    color: '#a7d2c0',
    cursor: 'pointer',
    fontWeight: 700,
    textTransform: 'uppercase',
    fontSize: 11,
  },
  sectionBody: { display: 'grid', gap: 8 },
  blockField: { display: 'grid', gap: 5 },
  row: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  label: { color: '#b9c8c3' },
  select: { ...controlBase, width: '100%', borderRadius: 6, padding: '7px 8px' },
  inlineControls: { display: 'flex', alignItems: 'center', gap: 8 },
  numberInput: { ...controlBase, width: 86, borderRadius: 6, padding: '6px 7px' },
  smallButton: { ...controlBase, borderRadius: 6, padding: '7px 9px', cursor: 'pointer' },
  sliderLabel: { display: 'flex', justifyContent: 'space-between', gap: 10, color: '#b9c8c3' },
  slider: { width: '100%', accentColor: '#88c7a8' },
  colorInput: { width: 48, height: 28, padding: 0, border: 0, borderRadius: 6, cursor: 'pointer', background: 'transparent' },
  checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, color: '#b9c8c3' },
  textarea: {
    ...controlBase,
    width: '100%',
    minHeight: 138,
    borderRadius: 6,
    padding: 8,
    resize: 'vertical',
    fontFamily: 'Consolas, monospace',
    fontSize: 11,
  },
  actions: { display: 'flex', gap: 8 },
  libraryList: { display: 'grid', gap: 8 },
  libraryEmpty: { color: '#7f918c' },
  libraryItem: { display: 'grid', gap: 6, padding: 8, border: '1px solid rgba(223, 229, 233, 0.12)', borderRadius: 6 },
  libraryActions: { display: 'flex', gap: 8 },
  primaryButton: {
    flex: 1,
    border: 0,
    borderRadius: 6,
    padding: '9px 10px',
    color: '#0e1814',
    background: '#9fe0bc',
    cursor: 'pointer',
    fontWeight: 700,
  },
  secondaryButton: { ...controlBase, borderRadius: 6, padding: '9px 10px', cursor: 'pointer' },
  dangerButton: { ...controlBase, borderRadius: 6, padding: '9px 10px', cursor: 'pointer', color: '#ffb7b0' },
  message: { margin: 0, color: '#9fe0bc', fontSize: 12 },
  footer: { margin: '12px 0 0', color: '#7f918c', fontSize: 11 },
  subcard: { display: 'grid', gap: 8, padding: 8, border: '1px solid rgba(223, 229, 233, 0.12)', borderRadius: 6 },
}
