export const OUTDOOR_DAY_ATMOSPHERE = Object.freeze({
  exposure: 1.08,
  background: '#c0e8fa',
  fog: '#d7eef5',
  fogDensity: 0.0011,
  sunDirection: [0.48, 0.78, 0.24],
  sunColor: '#fff0b8',
  sunIntensityOutside: 4.2,
  sunIntensityFromInside: 3.8,
  skyLightColor: '#d5edff',
  groundLightColor: '#63a75b',
  hemisphereIntensityOutside: 1.75,
  hemisphereIntensityFromInside: 1.65,
  skyBrightness: 1.1,
  cloudCoverageBoost: 0.11,
  sky: Object.freeze({
    horizon: '#bfe8f9',
    zenith: '#79c6f2',
    cloudBase: '#fffef7',
    cloudWarm: '#fff2ce',
    cloudShade: '#c5d6ec',
  }),
  leaves: Object.freeze({
    shade: 0.5,
    highlight: 1.12,
    skyStrength: 0.82,
    sunStrength: 0.36,
  }),
})
