// Particle effect presets: pure JSON recipes rendered by ParticleEffect.jsx.
// Effects are never stored as code — only as these preset objects, so they can
// be edited with sliders, generated by AI, and saved/exported as JSON.

export const PARTICLE_CATEGORIES = [
  { value: 'impact', label: 'Impact' },
  { value: 'burst', label: 'Burst' },
  { value: 'loop', label: 'Loop' },
  { value: 'trail', label: 'Trail' },
  { value: 'death', label: 'Mort' },
]

export const EMITTER_SHAPES = [
  { value: 'point', label: 'Point' },
  { value: 'sphere', label: 'Sphère' },
  { value: 'cone', label: 'Cône' },
  { value: 'circle', label: 'Cercle' },
  { value: 'box', label: 'Boîte' },
]

export const EMITTER_MODES = [
  { value: 'burst', label: 'Burst (tout d\'un coup)' },
  { value: 'loop', label: 'Continu' },
]

export const EMITTER_TEXTURES = [
  { value: 'soft_glow', label: 'Rond doux' },
  { value: 'circle', label: 'Cercle' },
  { value: 'star', label: 'Étoile' },
  { value: 'spark', label: 'Étincelle' },
  { value: 'smoke', label: 'Fumée' },
  { value: 'flame', label: 'Flamme' },
]

export const EMITTER_BLENDINGS = [
  { value: 'additive', label: 'Additif (lumineux)' },
  { value: 'normal', label: 'Normal' },
]

export const MAX_EMITTERS = 4
export const MAX_PARTICLES_PER_EMITTER = 500

export const DEFAULT_EMITTER = {
  shape: 'sphere',
  mode: 'burst',
  count: 60,
  texture: 'soft_glow',
  blending: 'additive',
  colorStart: '#ffcc55',
  colorEnd: '#ff2200',
  alphaStart: 1,
  alphaEnd: 0,
  sizeStart: 0.3,
  sizeEnd: 0.05,
  sizeVariance: 0.3,
  speed: 2.5,
  speedVariance: 0.4,
  spread: 1,
  direction: [0, 1, 0],
  gravity: -1,
  turbulence: 0,
  rotationSpeed: 0,
  lifetime: 0.7,
  lifetimeVariance: 0.3,
  radius: 0.1,
  offset: [0, 0, 0],
  delay: 0,
}

export const DEFAULT_PARTICLE_PRESET = {
  id: 'new_effect',
  name: 'Nouvel effet',
  category: 'burst',
  duration: 0.8,
  loop: false,
  emitters: [{ ...DEFAULT_EMITTER }],
  light: {
    enabled: false,
    color: '#ffaa44',
    intensity: 2,
  },
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value))
}

function asNumber(value, fallback) {
  const number = Number(value)
  return Number.isFinite(number) ? number : fallback
}

function asColor(value, fallback) {
  return typeof value === 'string' && /^#[0-9a-fA-F]{6}$/.test(value) ? value : fallback
}

function asVec3(value, fallback) {
  if (!Array.isArray(value) || value.length < 3) return [...fallback]
  return [asNumber(value[0], fallback[0]), asNumber(value[1], fallback[1]), asNumber(value[2], fallback[2])]
}

function asEnum(value, options, fallback) {
  return options.some((option) => option.value === value) ? value : fallback
}

export function normalizeEmitter(raw = {}) {
  const base = DEFAULT_EMITTER
  return {
    shape: asEnum(raw.shape, EMITTER_SHAPES, base.shape),
    mode: asEnum(raw.mode, EMITTER_MODES, base.mode),
    count: clamp(Math.round(asNumber(raw.count, base.count)), 1, MAX_PARTICLES_PER_EMITTER),
    texture: asEnum(raw.texture, EMITTER_TEXTURES, base.texture),
    blending: asEnum(raw.blending, EMITTER_BLENDINGS, base.blending),
    colorStart: asColor(raw.colorStart, base.colorStart),
    colorEnd: asColor(raw.colorEnd, base.colorEnd),
    alphaStart: clamp(asNumber(raw.alphaStart, base.alphaStart), 0, 1),
    alphaEnd: clamp(asNumber(raw.alphaEnd, base.alphaEnd), 0, 1),
    sizeStart: clamp(asNumber(raw.sizeStart, base.sizeStart), 0, 4),
    sizeEnd: clamp(asNumber(raw.sizeEnd, base.sizeEnd), 0, 4),
    sizeVariance: clamp(asNumber(raw.sizeVariance, base.sizeVariance), 0, 1),
    speed: clamp(asNumber(raw.speed, base.speed), 0, 20),
    speedVariance: clamp(asNumber(raw.speedVariance, base.speedVariance), 0, 1),
    spread: clamp(asNumber(raw.spread, base.spread), 0, 1),
    direction: asVec3(raw.direction, base.direction),
    gravity: clamp(asNumber(raw.gravity, base.gravity), -20, 20),
    turbulence: clamp(asNumber(raw.turbulence, base.turbulence), 0, 3),
    rotationSpeed: clamp(asNumber(raw.rotationSpeed, base.rotationSpeed), -12, 12),
    lifetime: clamp(asNumber(raw.lifetime, base.lifetime), 0.05, 8),
    lifetimeVariance: clamp(asNumber(raw.lifetimeVariance, base.lifetimeVariance), 0, 1),
    radius: clamp(asNumber(raw.radius, base.radius), 0, 5),
    offset: asVec3(raw.offset, base.offset),
    delay: clamp(asNumber(raw.delay, base.delay), 0, 5),
  }
}

export function normalizeParticlePreset(raw = {}) {
  const emitters = Array.isArray(raw.emitters) && raw.emitters.length > 0
    ? raw.emitters.slice(0, MAX_EMITTERS).map(normalizeEmitter)
    : [{ ...DEFAULT_EMITTER }]
  const light = raw.light ?? {}
  return {
    id: typeof raw.id === 'string' && raw.id ? raw.id : 'new_effect',
    name: typeof raw.name === 'string' && raw.name ? raw.name : 'Nouvel effet',
    category: asEnum(raw.category, PARTICLE_CATEGORIES, 'burst'),
    duration: clamp(asNumber(raw.duration, 0.8), 0.1, 10),
    loop: Boolean(raw.loop),
    emitters,
    light: {
      enabled: Boolean(light.enabled),
      color: asColor(light.color, '#ffaa44'),
      intensity: clamp(asNumber(light.intensity, 2), 0, 12),
    },
  }
}

export const BUILTIN_PARTICLE_PRESETS = [
  {
    id: 'fireball_hit',
    name: 'Impact boule de feu',
    category: 'impact',
    duration: 0.8,
    loop: false,
    emitters: [
      {
        shape: 'sphere', mode: 'burst', count: 90, texture: 'soft_glow', blending: 'additive',
        colorStart: '#ffcc55', colorEnd: '#ff2200', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.35, sizeEnd: 0.02, sizeVariance: 0.4,
        speed: 3.2, speedVariance: 0.5, spread: 1, direction: [0, 1, 0],
        gravity: -2, turbulence: 0.3, rotationSpeed: 0,
        lifetime: 0.55, lifetimeVariance: 0.35, radius: 0.12, offset: [0, 0.2, 0], delay: 0,
      },
      {
        shape: 'sphere', mode: 'burst', count: 25, texture: 'spark', blending: 'additive',
        colorStart: '#fff2bb', colorEnd: '#ff7711', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.22, sizeEnd: 0.04, sizeVariance: 0.5,
        speed: 5.5, speedVariance: 0.4, spread: 1, direction: [0, 1, 0],
        gravity: -6, turbulence: 0, rotationSpeed: 4,
        lifetime: 0.45, lifetimeVariance: 0.3, radius: 0.05, offset: [0, 0.2, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'burst', count: 10, texture: 'smoke', blending: 'normal',
        colorStart: '#5a5048', colorEnd: '#2c2824', alphaStart: 0.55, alphaEnd: 0,
        sizeStart: 0.35, sizeEnd: 1.1, sizeVariance: 0.4,
        speed: 0.9, speedVariance: 0.5, spread: 0.7, direction: [0, 1, 0],
        gravity: 0.6, turbulence: 0.4, rotationSpeed: 0.8,
        lifetime: 0.9, lifetimeVariance: 0.3, radius: 0.15, offset: [0, 0.3, 0], delay: 0.05,
      },
    ],
    light: { enabled: true, color: '#ff6600', intensity: 4 },
  },
  {
    id: 'chest_open',
    name: 'Ouverture de coffre',
    category: 'burst',
    duration: 1.2,
    loop: false,
    emitters: [
      {
        shape: 'cone', mode: 'burst', count: 60, texture: 'star', blending: 'additive',
        colorStart: '#d9a6ff', colorEnd: '#7a2bd6', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.2, sizeEnd: 0.05, sizeVariance: 0.5,
        speed: 3.4, speedVariance: 0.4, spread: 0.45, direction: [0, 1, 0],
        gravity: -3.4, turbulence: 0.2, rotationSpeed: 5,
        lifetime: 1, lifetimeVariance: 0.3, radius: 0.25, offset: [0, 0.4, 0], delay: 0,
      },
      {
        shape: 'circle', mode: 'loop', count: 50, texture: 'soft_glow', blending: 'additive',
        colorStart: '#ffe9a8', colorEnd: '#cf9cff', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.1, sizeEnd: 0.03, sizeVariance: 0.4,
        speed: 0.9, speedVariance: 0.4, spread: 0.2, direction: [0, 1, 0],
        gravity: 0.4, turbulence: 0.5, rotationSpeed: 0,
        lifetime: 1, lifetimeVariance: 0.4, radius: 0.45, offset: [0, 0.15, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#b46cff', intensity: 3 },
  },
  {
    id: 'mob_death',
    name: 'Mort de mob',
    category: 'death',
    duration: 1.1,
    loop: false,
    emitters: [
      {
        shape: 'sphere', mode: 'burst', count: 35, texture: 'smoke', blending: 'normal',
        colorStart: '#8d8d96', colorEnd: '#3a3a42', alphaStart: 0.8, alphaEnd: 0,
        sizeStart: 0.4, sizeEnd: 1.3, sizeVariance: 0.4,
        speed: 1.3, speedVariance: 0.5, spread: 0.9, direction: [0, 1, 0],
        gravity: 0.7, turbulence: 0.5, rotationSpeed: 0.8,
        lifetime: 1, lifetimeVariance: 0.3, radius: 0.3, offset: [0, 0.6, 0], delay: 0,
      },
      {
        shape: 'sphere', mode: 'burst', count: 30, texture: 'soft_glow', blending: 'additive',
        colorStart: '#e8fbff', colorEnd: '#65d8e8', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.18, sizeEnd: 0.02, sizeVariance: 0.4,
        speed: 2.6, speedVariance: 0.4, spread: 1, direction: [0, 1, 0],
        gravity: -1.5, turbulence: 0.3, rotationSpeed: 0,
        lifetime: 0.7, lifetimeVariance: 0.3, radius: 0.25, offset: [0, 0.6, 0], delay: 0,
      },
    ],
    light: { enabled: false, color: '#9adfe8', intensity: 1.5 },
  },
  {
    id: 'heal_aura',
    name: 'Aura de soin',
    category: 'loop',
    duration: 2,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 70, texture: 'soft_glow', blending: 'additive',
        colorStart: '#aaffc3', colorEnd: '#2ecf6e', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.12, sizeEnd: 0.04, sizeVariance: 0.4,
        speed: 0.8, speedVariance: 0.4, spread: 0.15, direction: [0, 1, 0],
        gravity: 0.3, turbulence: 0.35, rotationSpeed: 0,
        lifetime: 1.4, lifetimeVariance: 0.4, radius: 0.55, offset: [0, 0.1, 0], delay: 0,
      },
      {
        shape: 'circle', mode: 'loop', count: 16, texture: 'star', blending: 'additive',
        colorStart: '#eafff0', colorEnd: '#7dffa9', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.14, sizeEnd: 0.05, sizeVariance: 0.5,
        speed: 0.55, speedVariance: 0.4, spread: 0.1, direction: [0, 1, 0],
        gravity: 0.2, turbulence: 0.2, rotationSpeed: 2,
        lifetime: 1.8, lifetimeVariance: 0.3, radius: 0.35, offset: [0, 0.2, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#5cff96', intensity: 1.6 },
  },
  {
    id: 'campfire',
    name: 'Feu de camp',
    category: 'loop',
    duration: 2,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 80, texture: 'flame', blending: 'additive',
        colorStart: '#ffd24d', colorEnd: '#e8330a', alphaStart: 0.95, alphaEnd: 0,
        sizeStart: 0.42, sizeEnd: 0.08, sizeVariance: 0.4,
        speed: 1.5, speedVariance: 0.35, spread: 0.12, direction: [0, 1, 0],
        gravity: 0.8, turbulence: 0.35, rotationSpeed: 0,
        lifetime: 0.85, lifetimeVariance: 0.35, radius: 0.22, offset: [0, 0.05, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 26, texture: 'smoke', blending: 'normal',
        colorStart: '#544c45', colorEnd: '#26221f', alphaStart: 0.4, alphaEnd: 0,
        sizeStart: 0.3, sizeEnd: 1, sizeVariance: 0.4,
        speed: 0.8, speedVariance: 0.4, spread: 0.25, direction: [0, 1, 0],
        gravity: 0.5, turbulence: 0.45, rotationSpeed: 0.6,
        lifetime: 2.2, lifetimeVariance: 0.3, radius: 0.1, offset: [0, 0.7, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 14, texture: 'spark', blending: 'additive',
        colorStart: '#ffe9a0', colorEnd: '#ff7711', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.07, sizeEnd: 0.02, sizeVariance: 0.5,
        speed: 1.9, speedVariance: 0.5, spread: 0.3, direction: [0, 1, 0],
        gravity: -0.8, turbulence: 0.8, rotationSpeed: 3,
        lifetime: 1.1, lifetimeVariance: 0.5, radius: 0.12, offset: [0, 0.2, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#ff8a2a', intensity: 3.2 },
  },
].map(normalizeParticlePreset)
