// Particle effect presets: pure JSON recipes rendered by ParticleEffect.jsx.
// Effects are never stored as code — only as these preset objects, so they can
// be edited with sliders, generated by AI, and saved/exported as JSON.

export const PARTICLE_CATEGORIES = [
  { value: 'impact', label: 'Impact' },
  { value: 'burst', label: 'Burst' },
  { value: 'loop', label: 'Loop' },
  { value: 'trail', label: 'Trail' },
  { value: 'death', label: 'Mort' },
]

export const EMITTER_SHAPES = [
  { value: 'point', label: 'Point' },
  { value: 'sphere', label: 'Sphère' },
  { value: 'cone', label: 'Cône' },
  { value: 'circle', label: 'Cercle' },
  { value: 'ring', label: 'Anneau' },
  { value: 'box', label: 'Boîte' },
]

export const EMITTER_MODES = [
  { value: 'burst', label: 'Burst (tout d\'un coup)' },
  { value: 'loop', label: 'Continu' },
]

export const EMITTER_TEXTURES = [
  { value: 'soft_glow', label: 'Rond doux' },
  { value: 'circle', label: 'Cercle' },
  { value: 'star', label: 'Étoile' },
  { value: 'spark', label: 'Étincelle' },
  { value: 'smoke', label: 'Fumée' },
  { value: 'flame', label: 'Flamme' },
]

export const EMITTER_BLENDINGS = [
  { value: 'additive', label: 'Additif (lumineux)' },
  { value: 'normal', label: 'Normal' },
]

export const MAX_EMITTERS = 4
export const MAX_PARTICLES_PER_EMITTER = 500
export const MAX_SHELLS = 2
export const MAX_GROUND_RINGS = 3
export const MAX_GROUND_ZONES = 3

export const DEFAULT_EMITTER = {
  shape: 'sphere',
  mode: 'burst',
  count: 60,
  texture: 'soft_glow',
  blending: 'additive',
  colorStart: '#ffcc55',
  colorEnd: '#ff2200',
  alphaStart: 1,
  alphaEnd: 0,
  sizeStart: 0.3,
  sizeEnd: 0.05,
  sizeVariance: 0.3,
  speed: 2.5,
  motionScale: 1,
  speedVariance: 0.4,
  spread: 1,
  direction: [0, 1, 0],
  gravity: -1,
  turbulence: 0,
  rotationSpeed: 0,
  lifetime: 0.7,
  lifetimeVariance: 0.3,
  radius: 0.1,
  radiusEnd: 0.1,
  offset: [0, 0, 0],
  delay: 0,
}

// Noise-displaced shader shell ("energy ball"), rendered by ShaderShell.jsx.
// Same technique as the in-game fireball flame, but fully preset-driven.
export const DEFAULT_SHELL = {
  radius: 0.25,
  distortion: 0.4,
  noiseScale: 1,
  speed: 1,
  colorHot: '#ffeb61',
  colorMid: '#ff4705',
  colorDark: '#6b0700',
  opacity: 0.85,
  wobble: 1,
  spin: 1,
  scaleEnd: 1,
  fadeOut: true,
  offset: [0, 0.9, 0],
}

export const DEFAULT_GROUND_RING = {
  name: 'Anneau incandescent',
  enabled: true,
  delay: 0,
  duration: 0.9,
  startRadius: 0.35,
  endRadius: 6,
  thickness: 0.58,
  edgeSoftness: 0.28,
  noiseScale: 5,
  noiseStrength: 0.55,
  flowSpeed: 1.4,
  flameHeight: 1,
  flameFrequency: 9,
  intensity: 3,
  opacity: 0.9,
  colorHot: '#fff3b0',
  colorMid: '#ff5a1f',
  colorDark: '#8f0712',
  offsetY: 0.06,
  fadeOut: true,
}

export const DEFAULT_GROUND_ZONE = {
  name: 'Zone incandescente',
  enabled: true,
  delay: 0,
  duration: 4,
  startRadius: 1.5,
  endRadius: 1.5,
  edgeSoftness: 0.22,
  noiseScale: 4.5,
  noiseStrength: 0.16,
  flowSpeed: 0.7,
  pulseSpeed: 2.2,
  rimThickness: 0.16,
  intensity: 2.2,
  opacity: 0.65,
  colorHot: '#ffcf70',
  colorMid: '#d92818',
  colorDark: '#47030b',
  offsetY: 0.045,
  fadeIn: true,
  fadeOut: true,
}

export const DEFAULT_PARTICLE_PRESET = {
  id: 'new_effect',
  name: 'Nouvel effet',
  category: 'burst',
  duration: 0.8,
  loop: false,
  emitters: [{ ...DEFAULT_EMITTER }],
  shells: [],
  groundRings: [],
  groundZones: [],
  light: {
    enabled: false,
    color: '#ffaa44',
    intensity: 2,
  },
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value))
}

function asNumber(value, fallback) {
  const number = Number(value)
  return Number.isFinite(number) ? number : fallback
}

function asColor(value, fallback) {
  return typeof value === 'string' && /^#[0-9a-fA-F]{6}$/.test(value) ? value : fallback
}

function asVec3(value, fallback) {
  if (!Array.isArray(value) || value.length < 3) return [...fallback]
  return [asNumber(value[0], fallback[0]), asNumber(value[1], fallback[1]), asNumber(value[2], fallback[2])]
}

function asEnum(value, options, fallback) {
  return options.some((option) => option.value === value) ? value : fallback
}

export function normalizeEmitter(raw = {}) {
  const base = DEFAULT_EMITTER
  const radius = clamp(asNumber(raw.radius, base.radius), 0, 30)
  return {
    shape: asEnum(raw.shape, EMITTER_SHAPES, base.shape),
    mode: asEnum(raw.mode, EMITTER_MODES, base.mode),
    count: clamp(Math.round(asNumber(raw.count, base.count)), 1, MAX_PARTICLES_PER_EMITTER),
    texture: asEnum(raw.texture, EMITTER_TEXTURES, base.texture),
    blending: asEnum(raw.blending, EMITTER_BLENDINGS, base.blending),
    colorStart: asColor(raw.colorStart, base.colorStart),
    colorEnd: asColor(raw.colorEnd, base.colorEnd),
    alphaStart: clamp(asNumber(raw.alphaStart, base.alphaStart), 0, 1),
    alphaEnd: clamp(asNumber(raw.alphaEnd, base.alphaEnd), 0, 1),
    sizeStart: clamp(asNumber(raw.sizeStart, base.sizeStart), 0, 4),
    sizeEnd: clamp(asNumber(raw.sizeEnd, base.sizeEnd), 0, 4),
    sizeVariance: clamp(asNumber(raw.sizeVariance, base.sizeVariance), 0, 1),
    speed: clamp(asNumber(raw.speed, base.speed), 0, 20),
    motionScale: clamp(asNumber(raw.motionScale, base.motionScale), 0, 1),
    speedVariance: clamp(asNumber(raw.speedVariance, base.speedVariance), 0, 1),
    spread: clamp(asNumber(raw.spread, base.spread), 0, 1),
    direction: asVec3(raw.direction, base.direction),
    gravity: clamp(asNumber(raw.gravity, base.gravity), -20, 20),
    turbulence: clamp(asNumber(raw.turbulence, base.turbulence), 0, 3),
    rotationSpeed: clamp(asNumber(raw.rotationSpeed, base.rotationSpeed), -12, 12),
    lifetime: clamp(asNumber(raw.lifetime, base.lifetime), 0.05, 8),
    lifetimeVariance: clamp(asNumber(raw.lifetimeVariance, base.lifetimeVariance), 0, 1),
    radius,
    radiusEnd: clamp(asNumber(raw.radiusEnd, radius), 0, 30),
    offset: asVec3(raw.offset, base.offset),
    delay: clamp(asNumber(raw.delay, base.delay), 0, 5),
  }
}

export function normalizeShell(raw = {}) {
  const base = DEFAULT_SHELL
  return {
    radius: clamp(asNumber(raw.radius, base.radius), 0.02, 3),
    distortion: clamp(asNumber(raw.distortion, base.distortion), 0, 1.2),
    noiseScale: clamp(asNumber(raw.noiseScale, base.noiseScale), 0.2, 4),
    speed: clamp(asNumber(raw.speed, base.speed), 0, 4),
    colorHot: asColor(raw.colorHot, base.colorHot),
    colorMid: asColor(raw.colorMid, base.colorMid),
    colorDark: asColor(raw.colorDark, base.colorDark),
    opacity: clamp(asNumber(raw.opacity, base.opacity), 0, 1),
    wobble: clamp(asNumber(raw.wobble, base.wobble), 0, 2.5),
    spin: clamp(asNumber(raw.spin, base.spin), -4, 4),
    scaleEnd: clamp(asNumber(raw.scaleEnd, base.scaleEnd), 0, 4),
    fadeOut: raw.fadeOut === undefined ? base.fadeOut : Boolean(raw.fadeOut),
    offset: asVec3(raw.offset, base.offset),
  }
}

export function normalizeGroundRing(raw = {}) {
  const base = DEFAULT_GROUND_RING
  return {
    name: typeof raw.name === 'string' && raw.name ? raw.name.slice(0, 80) : base.name,
    enabled: raw.enabled === undefined ? base.enabled : Boolean(raw.enabled),
    delay: clamp(asNumber(raw.delay, base.delay), 0, 10),
    duration: clamp(asNumber(raw.duration, base.duration), 0.05, 10),
    startRadius: clamp(asNumber(raw.startRadius, base.startRadius), 0.02, 30),
    endRadius: clamp(asNumber(raw.endRadius, base.endRadius), 0.02, 30),
    thickness: clamp(asNumber(raw.thickness, base.thickness), 0.03, 5),
    edgeSoftness: clamp(asNumber(raw.edgeSoftness, base.edgeSoftness), 0.01, 1),
    noiseScale: clamp(asNumber(raw.noiseScale, base.noiseScale), 0.2, 20),
    noiseStrength: clamp(asNumber(raw.noiseStrength, base.noiseStrength), 0, 1.5),
    flowSpeed: clamp(asNumber(raw.flowSpeed, base.flowSpeed), -6, 6),
    flameHeight: clamp(asNumber(raw.flameHeight, base.flameHeight), 0, 2),
    flameFrequency: clamp(asNumber(raw.flameFrequency, base.flameFrequency), 1, 30),
    intensity: clamp(asNumber(raw.intensity, base.intensity), 0, 8),
    opacity: clamp(asNumber(raw.opacity, base.opacity), 0, 1),
    colorHot: asColor(raw.colorHot, base.colorHot),
    colorMid: asColor(raw.colorMid, base.colorMid),
    colorDark: asColor(raw.colorDark, base.colorDark),
    offsetY: clamp(asNumber(raw.offsetY, base.offsetY), -1, 3),
    fadeOut: raw.fadeOut === undefined ? base.fadeOut : Boolean(raw.fadeOut),
  }
}

export function normalizeGroundZone(raw = {}) {
  const base = DEFAULT_GROUND_ZONE
  return {
    name: typeof raw.name === 'string' && raw.name ? raw.name.slice(0, 80) : base.name,
    enabled: raw.enabled === undefined ? base.enabled : Boolean(raw.enabled),
    delay: clamp(asNumber(raw.delay, base.delay), 0, 10),
    duration: clamp(asNumber(raw.duration, base.duration), 0.05, 30),
    startRadius: clamp(asNumber(raw.startRadius, base.startRadius), 0.02, 30),
    endRadius: clamp(asNumber(raw.endRadius, base.endRadius), 0.02, 30),
    edgeSoftness: clamp(asNumber(raw.edgeSoftness, base.edgeSoftness), 0.01, 1),
    noiseScale: clamp(asNumber(raw.noiseScale, base.noiseScale), 0.2, 20),
    noiseStrength: clamp(asNumber(raw.noiseStrength, base.noiseStrength), 0, 1),
    flowSpeed: clamp(asNumber(raw.flowSpeed, base.flowSpeed), -6, 6),
    pulseSpeed: clamp(asNumber(raw.pulseSpeed, base.pulseSpeed), 0, 12),
    rimThickness: clamp(asNumber(raw.rimThickness, base.rimThickness), 0.01, 0.8),
    intensity: clamp(asNumber(raw.intensity, base.intensity), 0, 8),
    opacity: clamp(asNumber(raw.opacity, base.opacity), 0, 1),
    colorHot: asColor(raw.colorHot, base.colorHot),
    colorMid: asColor(raw.colorMid, base.colorMid),
    colorDark: asColor(raw.colorDark, base.colorDark),
    offsetY: clamp(asNumber(raw.offsetY, base.offsetY), -1, 3),
    fadeIn: raw.fadeIn === undefined ? base.fadeIn : Boolean(raw.fadeIn),
    fadeOut: raw.fadeOut === undefined ? base.fadeOut : Boolean(raw.fadeOut),
  }
}

export function normalizeParticlePreset(raw = {}) {
  const shells = Array.isArray(raw.shells)
    ? raw.shells.slice(0, MAX_SHELLS).map(normalizeShell)
    : []
  const groundRings = Array.isArray(raw.groundRings)
    ? raw.groundRings.slice(0, MAX_GROUND_RINGS).map(normalizeGroundRing)
    : []
  const groundZones = Array.isArray(raw.groundZones)
    ? raw.groundZones.slice(0, MAX_GROUND_ZONES).map(normalizeGroundZone)
    : []
  const emitters = Array.isArray(raw.emitters) && raw.emitters.length > 0
    ? raw.emitters.slice(0, MAX_EMITTERS).map(normalizeEmitter)
    : (Array.isArray(raw.emitters) && (shells.length > 0 || groundRings.length > 0 || groundZones.length > 0)
        ? []
        : [{ ...DEFAULT_EMITTER }])
  const light = raw.light ?? {}
  return {
    id: typeof raw.id === 'string' && raw.id ? raw.id : 'new_effect',
    name: typeof raw.name === 'string' && raw.name ? raw.name : 'Nouvel effet',
    category: asEnum(raw.category, PARTICLE_CATEGORIES, 'burst'),
    duration: clamp(asNumber(raw.duration, 0.8), 0.1, 10),
    loop: Boolean(raw.loop),
    emitters,
    shells,
    groundRings,
    groundZones,
    light: {
      enabled: Boolean(light.enabled),
      color: asColor(light.color, '#ffaa44'),
      intensity: clamp(asNumber(light.intensity, 2), 0, 12),
    },
  }
}

export const BUILTIN_PARTICLE_PRESETS = [
  {
    id: 'slime_shockwave_fire',
    name: 'Onde enflammée du Roi Slime',
    category: 'impact',
    duration: 1.15,
    loop: false,
    emitters: [
      {
        shape: 'ring', mode: 'burst', count: 90, texture: 'flame', blending: 'additive',
        colorStart: '#fff0a6', colorEnd: '#e8170c', alphaStart: 0.95, alphaEnd: 0,
        sizeStart: 0.3, sizeEnd: 0.05, sizeVariance: 0.55,
        speed: 1.6, speedVariance: 0.5, spread: 0.35, direction: [0, 1, 0],
        gravity: 0.45, turbulence: 0.65, rotationSpeed: 1.8,
        lifetime: 0.82, lifetimeVariance: 0.2, radius: 0.35, radiusEnd: 6, offset: [0, 0.08, 0], delay: 0.02,
      },
      {
        shape: 'ring', mode: 'burst', count: 36, texture: 'spark', blending: 'additive',
        colorStart: '#fff7cf', colorEnd: '#ff451c', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.12, sizeEnd: 0.015, sizeVariance: 0.5,
        speed: 3.2, speedVariance: 0.55, spread: 0.8, direction: [0, 1, 0],
        gravity: -2.8, turbulence: 0.35, rotationSpeed: 4,
        lifetime: 0.82, lifetimeVariance: 0.25, radius: 0.35, radiusEnd: 6, offset: [0, 0.08, 0], delay: 0.02,
      },
    ],
    shells: [],
    groundRings: [{ ...DEFAULT_GROUND_RING }],
    light: { enabled: false, color: '#ff4b1f', intensity: 3 },
  },
  {
    id: 'slime_projectile_zone',
    name: 'Zone brûlante du Roi Slime',
    category: 'loop',
    duration: 7.2,
    loop: false,
    emitters: [],
    shells: [],
    groundRings: [],
    groundZones: [{
      ...DEFAULT_GROUND_ZONE,
      name: 'Flaque brûlante',
      duration: 7.2,
      startRadius: 1.75,
      endRadius: 1.82,
      edgeSoftness: 0.24,
      noiseScale: 5.8,
      noiseStrength: 0.2,
      flowSpeed: 0.9,
      pulseSpeed: 2.6,
      rimThickness: 0.18,
      intensity: 2.7,
      opacity: 0.72,
      colorHot: '#ffc15a',
      colorMid: '#d92116',
      colorDark: '#3a0208',
      fadeIn: true,
      fadeOut: true,
    }],
    light: { enabled: false, color: '#ff321d', intensity: 2 },
  },
  {
    id: 'fireball_hit',
    name: 'Impact boule de feu',
    category: 'impact',
    duration: 0.8,
    loop: false,
    emitters: [
      {
        shape: 'sphere', mode: 'burst', count: 90, texture: 'soft_glow', blending: 'additive',
        colorStart: '#ffcc55', colorEnd: '#ff2200', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.35, sizeEnd: 0.02, sizeVariance: 0.4,
        speed: 3.2, speedVariance: 0.5, spread: 1, direction: [0, 1, 0],
        gravity: -2, turbulence: 0.3, rotationSpeed: 0,
        lifetime: 0.55, lifetimeVariance: 0.35, radius: 0.12, offset: [0, 0.2, 0], delay: 0,
      },
      {
        shape: 'sphere', mode: 'burst', count: 25, texture: 'spark', blending: 'additive',
        colorStart: '#fff2bb', colorEnd: '#ff7711', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.22, sizeEnd: 0.04, sizeVariance: 0.5,
        speed: 5.5, speedVariance: 0.4, spread: 1, direction: [0, 1, 0],
        gravity: -6, turbulence: 0, rotationSpeed: 4,
        lifetime: 0.45, lifetimeVariance: 0.3, radius: 0.05, offset: [0, 0.2, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'burst', count: 10, texture: 'smoke', blending: 'normal',
        colorStart: '#5a5048', colorEnd: '#2c2824', alphaStart: 0.55, alphaEnd: 0,
        sizeStart: 0.35, sizeEnd: 1.1, sizeVariance: 0.4,
        speed: 0.9, speedVariance: 0.5, spread: 0.7, direction: [0, 1, 0],
        gravity: 0.6, turbulence: 0.4, rotationSpeed: 0.8,
        lifetime: 0.9, lifetimeVariance: 0.3, radius: 0.15, offset: [0, 0.3, 0], delay: 0.05,
      },
    ],
    light: { enabled: true, color: '#ff6600', intensity: 4 },
  },
  {
    id: 'fireball_projectile',
    name: 'Projectile boule de feu',
    category: 'trail',
    duration: 1.5,
    loop: true,
    shells: [
      {
        radius: 0.2, distortion: 0.42, noiseScale: 1, speed: 1,
        colorHot: '#ffeb61', colorMid: '#ff4705', colorDark: '#6b0700',
        opacity: 0.85, wobble: 1, spin: 1, scaleEnd: 1, fadeOut: false,
        offset: [0, 0.9, 0],
      },
    ],
    emitters: [
      {
        shape: 'point', mode: 'loop', count: 40, texture: 'flame', blending: 'additive',
        colorStart: '#ffb347', colorEnd: '#d61e00', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.18, sizeEnd: 0.03, sizeVariance: 0.4,
        speed: 0.7, speedVariance: 0.4, spread: 0.55, direction: [0, 0.6, 0],
        gravity: 0.4, turbulence: 0.5, rotationSpeed: 1.5,
        lifetime: 0.5, lifetimeVariance: 0.4, radius: 0.16, offset: [0, 0.9, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 14, texture: 'spark', blending: 'additive',
        colorStart: '#fff2bb', colorEnd: '#ff7711', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.08, sizeEnd: 0.02, sizeVariance: 0.5,
        speed: 1.4, speedVariance: 0.5, spread: 0.9, direction: [0, 0.4, 0],
        gravity: -2.2, turbulence: 0.4, rotationSpeed: 4,
        lifetime: 0.45, lifetimeVariance: 0.4, radius: 0.12, offset: [0, 0.9, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 12, texture: 'smoke', blending: 'normal',
        colorStart: '#4d4540', colorEnd: '#262220', alphaStart: 0.35, alphaEnd: 0,
        sizeStart: 0.2, sizeEnd: 0.6, sizeVariance: 0.4,
        speed: 0.6, speedVariance: 0.4, spread: 0.4, direction: [0, 1, 0],
        gravity: 0.4, turbulence: 0.4, rotationSpeed: 0.7,
        lifetime: 1, lifetimeVariance: 0.4, radius: 0.08, offset: [0, 1, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#ff7722', intensity: 3 },
  },
  {
    id: 'chest_open',
    name: 'Ouverture de coffre',
    category: 'burst',
    duration: 1.2,
    loop: false,
    emitters: [
      {
        shape: 'cone', mode: 'burst', count: 60, texture: 'star', blending: 'additive',
        colorStart: '#d9a6ff', colorEnd: '#7a2bd6', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.2, sizeEnd: 0.05, sizeVariance: 0.5,
        speed: 3.4, speedVariance: 0.4, spread: 0.45, direction: [0, 1, 0],
        gravity: -3.4, turbulence: 0.2, rotationSpeed: 5,
        lifetime: 1, lifetimeVariance: 0.3, radius: 0.25, offset: [0, 0.4, 0], delay: 0,
      },
      {
        shape: 'circle', mode: 'loop', count: 50, texture: 'soft_glow', blending: 'additive',
        colorStart: '#ffe9a8', colorEnd: '#cf9cff', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.1, sizeEnd: 0.03, sizeVariance: 0.4,
        speed: 0.9, speedVariance: 0.4, spread: 0.2, direction: [0, 1, 0],
        gravity: 0.4, turbulence: 0.5, rotationSpeed: 0,
        lifetime: 1, lifetimeVariance: 0.4, radius: 0.45, offset: [0, 0.15, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#b46cff', intensity: 3 },
  },
  {
    id: 'interaction',
    name: 'Interaction',
    category: 'loop',
    duration: 1.8,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 56, texture: 'star', blending: 'additive',
        colorStart: '#e9ddff', colorEnd: '#8b5cf6', alphaStart: 0.95, alphaEnd: 0,
        sizeStart: 0.12, sizeEnd: 0.03, sizeVariance: 0.45,
        speed: 0.65, speedVariance: 0.35, spread: 0.12, direction: [0, 1, 0],
        gravity: 0.18, turbulence: 0.35, rotationSpeed: 2.8,
        lifetime: 1.45, lifetimeVariance: 0.35, radius: 0.42, offset: [0, 0.08, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 20, texture: 'soft_glow', blending: 'additive',
        colorStart: '#d8f7ff', colorEnd: '#b07cff', alphaStart: 0.85, alphaEnd: 0,
        sizeStart: 0.18, sizeEnd: 0.04, sizeVariance: 0.35,
        speed: 0.9, speedVariance: 0.4, spread: 0.45, direction: [0, 1, 0],
        gravity: 0.1, turbulence: 0.3, rotationSpeed: 0,
        lifetime: 1.1, lifetimeVariance: 0.35, radius: 0.18, offset: [0, 0.25, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#9f7aea', intensity: 1.8 },
  },
  {
    id: 'mob_death',
    name: 'Mort de mob',
    category: 'death',
    duration: 1.1,
    loop: false,
    emitters: [
      {
        shape: 'sphere', mode: 'burst', count: 35, texture: 'smoke', blending: 'normal',
        colorStart: '#8d8d96', colorEnd: '#3a3a42', alphaStart: 0.8, alphaEnd: 0,
        sizeStart: 0.4, sizeEnd: 1.3, sizeVariance: 0.4,
        speed: 1.3, speedVariance: 0.5, spread: 0.9, direction: [0, 1, 0],
        gravity: 0.7, turbulence: 0.5, rotationSpeed: 0.8,
        lifetime: 1, lifetimeVariance: 0.3, radius: 0.3, offset: [0, 0.6, 0], delay: 0,
      },
      {
        shape: 'sphere', mode: 'burst', count: 30, texture: 'soft_glow', blending: 'additive',
        colorStart: '#e8fbff', colorEnd: '#65d8e8', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.18, sizeEnd: 0.02, sizeVariance: 0.4,
        speed: 2.6, speedVariance: 0.4, spread: 1, direction: [0, 1, 0],
        gravity: -1.5, turbulence: 0.3, rotationSpeed: 0,
        lifetime: 0.7, lifetimeVariance: 0.3, radius: 0.25, offset: [0, 0.6, 0], delay: 0,
      },
    ],
    light: { enabled: false, color: '#9adfe8', intensity: 1.5 },
  },
  {
    id: 'heal_aura',
    name: 'Aura de soin',
    category: 'loop',
    duration: 2,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 70, texture: 'soft_glow', blending: 'additive',
        colorStart: '#aaffc3', colorEnd: '#2ecf6e', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.12, sizeEnd: 0.04, sizeVariance: 0.4,
        speed: 0.8, speedVariance: 0.4, spread: 0.15, direction: [0, 1, 0],
        gravity: 0.3, turbulence: 0.35, rotationSpeed: 0,
        lifetime: 1.4, lifetimeVariance: 0.4, radius: 0.55, offset: [0, 0.1, 0], delay: 0,
      },
      {
        shape: 'circle', mode: 'loop', count: 16, texture: 'star', blending: 'additive',
        colorStart: '#eafff0', colorEnd: '#7dffa9', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.14, sizeEnd: 0.05, sizeVariance: 0.5,
        speed: 0.55, speedVariance: 0.4, spread: 0.1, direction: [0, 1, 0],
        gravity: 0.2, turbulence: 0.2, rotationSpeed: 2,
        lifetime: 1.8, lifetimeVariance: 0.3, radius: 0.35, offset: [0, 0.2, 0], delay: 0,
      },
    ],
    // Lumière désactivée : sa pointLight s'allumait pile sur le joueur et forçait
    // Three.js à recompiler les matériaux custom de l'avatar (shaders de teinte
    // patchés) à chaque soin = freeze. Les particules additives suffisent au halo.
    light: { enabled: false, color: '#5cff96', intensity: 1.6 },
  },
  {
    id: 'campfire',
    name: 'Feu de camp',
    category: 'loop',
    duration: 2,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 80, texture: 'flame', blending: 'additive',
        colorStart: '#ffd24d', colorEnd: '#e8330a', alphaStart: 0.95, alphaEnd: 0,
        sizeStart: 0.42, sizeEnd: 0.08, sizeVariance: 0.4,
        speed: 1.5, speedVariance: 0.35, spread: 0.12, direction: [0, 1, 0],
        gravity: 0.8, turbulence: 0.35, rotationSpeed: 0,
        lifetime: 0.85, lifetimeVariance: 0.35, radius: 0.22, offset: [0, 0.05, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 26, texture: 'smoke', blending: 'normal',
        colorStart: '#544c45', colorEnd: '#26221f', alphaStart: 0.4, alphaEnd: 0,
        sizeStart: 0.3, sizeEnd: 1, sizeVariance: 0.4,
        speed: 0.8, speedVariance: 0.4, spread: 0.25, direction: [0, 1, 0],
        gravity: 0.5, turbulence: 0.45, rotationSpeed: 0.6,
        lifetime: 2.2, lifetimeVariance: 0.3, radius: 0.1, offset: [0, 0.7, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 14, texture: 'spark', blending: 'additive',
        colorStart: '#ffe9a0', colorEnd: '#ff7711', alphaStart: 1, alphaEnd: 0,
        sizeStart: 0.07, sizeEnd: 0.02, sizeVariance: 0.5,
        speed: 1.9, speedVariance: 0.5, spread: 0.3, direction: [0, 1, 0],
        gravity: -0.8, turbulence: 0.8, rotationSpeed: 3,
        lifetime: 1.1, lifetimeVariance: 0.5, radius: 0.12, offset: [0, 0.2, 0], delay: 0,
      },
    ],
    light: { enabled: true, color: '#ff8a2a', intensity: 3.2 },
  },
  {
    id: 'cheat_sword_aura',
    name: 'Aura de l’Épée du Roi Slime',
    category: 'trail',
    duration: 1.6,
    loop: true,
    emitters: [
      {
        shape: 'circle', mode: 'loop', count: 34, texture: 'spark', blending: 'additive',
        colorStart: '#fff4a8', colorEnd: '#43d9ff', alphaStart: 0.9, alphaEnd: 0,
        sizeStart: 0.09, sizeEnd: 0.015, sizeVariance: 0.45,
        speed: 0.55, speedVariance: 0.35, spread: 0.22, direction: [0, 1, 0],
        gravity: 0.08, turbulence: 0.3, rotationSpeed: 3,
        lifetime: 0.9, lifetimeVariance: 0.3, radius: 0.58, offset: [0, 0, 0], delay: 0,
      },
      {
        shape: 'point', mode: 'loop', count: 18, texture: 'soft_glow', blending: 'additive',
        colorStart: '#76e7ff', colorEnd: '#126bff', alphaStart: 0.55, alphaEnd: 0,
        sizeStart: 0.14, sizeEnd: 0.025, sizeVariance: 0.35,
        speed: 0.32, speedVariance: 0.4, spread: 0.5, direction: [0, 1, 0],
        gravity: 0.05, turbulence: 0.4, rotationSpeed: 0,
        lifetime: 1.15, lifetimeVariance: 0.35, radius: 0.34, offset: [0, 0, 0], delay: 0,
      },
    ],
    light: { enabled: false, color: '#66e0ff', intensity: 1.5 },
  },
].map(normalizeParticlePreset)
