export const GAME_TREE_LIBRARY = {
  ashMedium: {
    id: 'ashMedium',
    name: 'Ash medium',
    config: {
      preset: 'Ash Medium',
      seed: 717902,
      position: { x: 0, y: -0.4, z: 0 },
      rotationY: 0,
      scale: 0.12,
      snapToGround: true,
      bark: { tint: 14207690 },
      branch: {
        levels: null,
        trunkLength: null,
        trunkRadius: null,
        firstBranchAngle: null,
        secondBranchAngle: null,
        trunkChildren: null,
        branchChildren: null,
        trunkGnarliness: null,
        forceStrength: null,
      },
      leaves: {
        tint: 15657192,
        size: 5.5,
        count: 55,
        start: 0.42,
        sizeVariance: null,
        alphaTest: null,
        normalMode: 'generated',
        normalStrength: 0.78,
        colorMode: 'gameGrass',
        colorVariation: 0.34,
        hueShift: 0.03,
        saturation: 0.98,
        brightness: 1,
      },
    },
  },
  ashSmall: {
    id: 'ashSmall',
    name: 'Ash small',
    config: {
      preset: 'Ash Medium',
      seed: 346181,
      position: { x: 0, y: -0.4, z: 0 },
      rotationY: 0,
      scale: 0.1,
      snapToGround: true,
      bark: { tint: 14207690 },
      branch: {
        levels: null,
        trunkLength: null,
        trunkRadius: null,
        firstBranchAngle: null,
        secondBranchAngle: null,
        trunkChildren: null,
        branchChildren: null,
        trunkGnarliness: null,
        forceStrength: null,
      },
      leaves: {
        tint: 15657192,
        size: 4.8,
        count: 46,
        start: 0.42,
        sizeVariance: null,
        alphaTest: null,
        normalMode: 'generated',
        normalStrength: 0.78,
        colorMode: 'gameGrass',
        colorVariation: 0.3,
        hueShift: -0.02,
        saturation: 0.98,
        brightness: 1,
      },
    },
  },
  ashYoung: {
    id: 'ashYoung',
    name: 'Ash young',
    config: {
      preset: 'Ash Medium',
      seed: 823441,
      position: { x: 0, y: -0.4, z: 0 },
      rotationY: 0,
      scale: 0.085,
      snapToGround: true,
      bark: { tint: 14207690 },
      branch: {
        levels: null,
        trunkLength: null,
        trunkRadius: null,
        firstBranchAngle: null,
        secondBranchAngle: null,
        trunkChildren: null,
        branchChildren: null,
        trunkGnarliness: null,
        forceStrength: null,
      },
      leaves: {
        tint: 15657192,
        size: 4.25,
        count: 38,
        start: 0.42,
        sizeVariance: null,
        alphaTest: null,
        normalMode: 'generated',
        normalStrength: 0.78,
        colorMode: 'gameGrass',
        colorVariation: 0.28,
        hueShift: 0.05,
        saturation: 0.98,
        brightness: 0.98,
      },
    },
  },
  ashDistant: {
    id: 'ashDistant',
    name: 'Ash distant',
    config: {
      preset: 'Ash Medium',
      seed: 927411,
      position: { x: 0, y: -0.4, z: 0 },
      rotationY: 0,
      scale: 0.096,
      snapToGround: true,
      bark: { tint: 14207690 },
      branch: {
        levels: null,
        trunkLength: null,
        trunkRadius: null,
        firstBranchAngle: null,
        secondBranchAngle: null,
        trunkChildren: null,
        branchChildren: null,
        trunkGnarliness: null,
        forceStrength: null,
      },
      leaves: {
        tint: 15657192,
        size: 4.55,
        count: 30,
        start: 0.42,
        sizeVariance: null,
        alphaTest: null,
        normalMode: 'generated',
        normalStrength: 0.78,
        colorMode: 'gameGrass',
        colorVariation: 0.28,
        hueShift: -0.04,
        saturation: 0.98,
        brightness: 0.98,
      },
    },
  },
}

export function getLibraryTreeConfig(variantId, placement) {
  const variant = GAME_TREE_LIBRARY[variantId] ?? GAME_TREE_LIBRARY.ashMedium
  return {
    ...variant.config,
    position: {
      ...variant.config.position,
      x: placement.x,
      z: placement.z,
    },
    rotationY: placement.rotationY ?? 0,
    scale: variant.config.scale * (placement.scaleMultiplier ?? 1),
  }
}
